{
 "title": "Laravel Horizon Monitoring",
 "description": "A Dashboard for the Laravel Horizon Prometheus Exporter",
 "tags": [
  "laravel",
  "horizon",
  "tasks"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Horizon Status",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 1, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "app_horizon_status" }
   ]
  },
  {
   "title": "Jobs in Queue",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(app_horizon_current_workload)"
    }
   ]
  },
  {
   "title": "Count Worker",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 11, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(app_horizon_current_processes)"
    }
   ]
  },
  {
   "title": "Failed Jobs",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(app_horizon_failed_jobs)" }
   ]
  },
  {
   "title": "Current Backlog per Queue",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "app_horizon_current_workload", "legendFormat": "{{queue}}" }
   ]
  },
  {
   "title": "Currently living processes per queue",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "app_horizon_current_processes", "legendFormat": "{{queue}}" }
   ]
  },
  {
   "title": "Failed Jobs",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "app_horizon_failed_jobs", "legendFormat": "Failed Jobs" }
   ]
  }
 ]
}